name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - name: Prepare Laravel Application
        run: |
            cp .env.example .env
            php artisan key:generate
      - uses: education/autograding@v1
